variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"


image: "maven:3.6.3-jdk-8"
#$CI_COMMIT_SHORT_SHA-SNAPSHOT

maven-dev:
  except:
    - 'master'
  script:
    - 'wget -O bukkit-1.8.8.jar --trust-server-names https://www.serverjars.com/api/fetchJar/bukkit/1.8.8'
    - 'mvn install:install-file -Dfile=bukkit-1.8.8.jar -DgroupId=org.bukkit -DartifactId=craftbukkit-nms -Dversion=v1_8_R3 -Dpackaging=jar'
    - 'wget -O bukkit-1.9.4.jar --trust-server-names https://www.serverjars.com/api/fetchJar/bukkit/1.9.4'
    - 'mvn install:install-file -Dfile=bukkit-1.9.4.jar -DgroupId=org.bukkit -DartifactId=craftbukkit-nms -Dversion=v1_9_R2 -Dpackaging=jar'
    - 'wget -O bukkit-1.10.2.jar --trust-server-names https://www.serverjars.com/api/fetchJar/bukkit/1.10.2'
    - 'mvn install:install-file -Dfile=bukkit-1.10.2.jar -DgroupId=org.bukkit -DartifactId=craftbukkit-nms -Dversion=v1_10_R1 -Dpackaging=jar'
    - 'wget -O bukkit-1.11.2.jar --trust-server-names https://www.serverjars.com/api/fetchJar/bukkit/1.11.2'
    - 'mvn install:install-file -Dfile=bukkit-1.11.2.jar -DgroupId=org.bukkit -DartifactId=craftbukkit-nms -Dversion=v1_11_R1 -Dpackaging=jar'
    - 'wget -O bukkit-1.12.2.jar --trust-server-names https://www.serverjars.com/api/fetchJar/bukkit/1.12.2'
    - 'mvn install:install-file -Dfile=bukkit-1.12.2.jar -DgroupId=org.bukkit -DartifactId=craftbukkit-nms -Dversion=v1_12_R1 -Dpackaging=jar'
    - 'wget -O bukkit-1.13.2.jar --trust-server-names https://www.serverjars.com/api/fetchJar/bukkit/1.13.2'
    - 'mvn install:install-file -Dfile=bukkit-1.13.2.jar -DgroupId=org.bukkit -DartifactId=craftbukkit-nms -Dversion=v1_13_R1 -Dpackaging=jar'
    - 'wget -O bukkit-1.14.4.jar --trust-server-names https://www.serverjars.com/api/fetchJar/bukkit/1.14.4'
    - 'mvn install:install-file -Dfile=bukkit-1.14.4.jar -DgroupId=org.bukkit -DartifactId=craftbukkit-nms -Dversion=v1_14_R1 -Dpackaging=jar'
    - 'wget -O bukkit-1.15.2.jar --trust-server-names https://www.serverjars.com/api/fetchJar/bukkit/1.15.2'
    - 'mvn install:install-file -Dfile=bukkit-1.15.2.jar -DgroupId=org.bukkit -DartifactId=craftbukkit-nms -Dversion=v1_15_R1 -Dpackaging=jar'
    - 'mvn versions:set -DnewVersion=20.3-SNAPSHOT'
    - 'mvn versions:update-child-modules'
    - 'mvn -DgitVer=git-$CI_COMMIT_SHORT_SHA- clean deploy -s ci_settings.xml'
  artifacts:
    paths:
      - bedwars-plugin/target/bedwars-*.jar
      - bedwars-api/target/apidocs
      - bedwars-api/target/bedwars-*.jar
    expire_in: 2 days

maven-rel:
  only:
    - 'master'
  script:
    - 'wget -O bukkit-1.8.8.jar --trust-server-names https://www.serverjars.com/api/fetchJar/bukkit/1.8.8'
    - 'mvn install:install-file -Dfile=bukkit-1.8.8.jar -DgroupId=org.bukkit -DartifactId=craftbukkit-nms -Dversion=v1_8_R3 -Dpackaging=jar'
    - 'wget -O bukkit-1.9.4.jar --trust-server-names https://www.serverjars.com/api/fetchJar/bukkit/1.9.4'
    - 'mvn install:install-file -Dfile=bukkit-1.9.4.jar -DgroupId=org.bukkit -DartifactId=craftbukkit-nms -Dversion=v1_9_R2 -Dpackaging=jar'
    - 'wget -O bukkit-1.10.2.jar --trust-server-names https://www.serverjars.com/api/fetchJar/bukkit/1.10.2'
    - 'mvn install:install-file -Dfile=bukkit-1.10.2.jar -DgroupId=org.bukkit -DartifactId=craftbukkit-nms -Dversion=v1_10_R1 -Dpackaging=jar'
    - 'wget -O bukkit-1.11.2.jar --trust-server-names https://www.serverjars.com/api/fetchJar/bukkit/1.11.2'
    - 'mvn install:install-file -Dfile=bukkit-1.11.2.jar -DgroupId=org.bukkit -DartifactId=craftbukkit-nms -Dversion=v1_11_R1 -Dpackaging=jar'
    - 'wget -O bukkit-1.12.2.jar --trust-server-names https://www.serverjars.com/api/fetchJar/bukkit/1.12.2'
    - 'mvn install:install-file -Dfile=bukkit-1.12.2.jar -DgroupId=org.bukkit -DartifactId=craftbukkit-nms -Dversion=v1_12_R1 -Dpackaging=jar'
    - 'wget -O bukkit-1.13.2.jar --trust-server-names https://www.serverjars.com/api/fetchJar/bukkit/1.13.2'
    - 'mvn install:install-file -Dfile=bukkit-1.13.2.jar -DgroupId=org.bukkit -DartifactId=craftbukkit-nms -Dversion=v1_13_R1 -Dpackaging=jar'
    - 'wget -O bukkit-1.14.4.jar --trust-server-names https://www.serverjars.com/api/fetchJar/bukkit/1.14.4'
    - 'mvn install:install-file -Dfile=bukkit-1.14.4.jar -DgroupId=org.bukkit -DartifactId=craftbukkit-nms -Dversion=v1_14_R1 -Dpackaging=jar'
    - 'wget -O bukkit-1.15.2.jar --trust-server-names https://www.serverjars.com/api/fetchJar/bukkit/1.15.2'
    - 'mvn install:install-file -Dfile=bukkit-1.15.2.jar -DgroupId=org.bukkit -DartifactId=craftbukkit-nms -Dversion=v1_15_R1 -Dpackaging=jar'
    - 'mvn versions:set -DnewVersion=20.3'
    - 'mvn versions:update-child-modules'
    - 'mvn -DgitVer='''' clean deploy -s ci_settings.xml'
  artifacts:
    paths:
      - bedwars-plugin/target/bedwars-*.jar
      - bedwars-api/target/apidocs
      - bedwars-api/target/bedwars-*.jar