image: "maven:latest"

maven-job:
  script:
    - 'cp /ci_settings.xml /root/.m2/settings.xml'
    - 'mvn clean deploy'
  artifacts:
    paths:
      - bedwars-plugin/target/bedwars-*.jar
    expire_in: 1 days