name: BedWars1058
api-version: '1.13'
version: 0.14beta-pre4
author: andrei1058
description: BedWars minigame by andrei1058
main: com.andrei1058.bedwars.Main
softdepend: [Vault,PlaceholderAPI,Citizens,Parties,SlimeWorldManager]
load: STARTUP